/**
 * 389. Find the Difference
 *
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Return the letter that was added to t
 */

/*
Algorithim:
- Create variable for string s count
- Create variable for string t count
- Find the total sum of letters in string s and convert to int
- Find the total sum of letters in string t and convert to int
- Create result variable for string s2 - s1.
- Subtract string t from string s.
- Convert string int back to character and return character.
 */
fun findTheDifference(s: String, t: String): Char {
    var newString = s + t
    var n = 0

    for (i in 0 until newString.length) {
        n = n xor newString[i].toInt()
    }
    return n.toChar()
}


/*
        var s1 = 0
        var s2 = 0
        s.forEach {
            s1 += it.toInt()
        }

        t.forEach {
            s2 += it.toInt()
        }

        val result = s2 - s1
        return result.toChar()
        // val sumOfFirst = s.sumOf { it.toInt() }
        // val sumOfSecond = t.sumOf{ it.toInt() }

        // val result = sumOfSecond - sumOfFirst
        // return result.toChar()
 */